var priceItem01 = 29.99;
var priceItem02 = 49.99;
var priceItem03 = 19.99;
var taxRate = 7;
var shoppingCartWithNoTaxes = priceItem01 + priceItem02 + priceItem03;
var costOfTaxes = priceItem01 * taxRate / 100 + priceItem02 * taxRate / 100 + priceItem03 * taxRate / 100;
var shoppingCartTotal = shoppingCartWithNoTaxes + costOfTaxes;
console.log("Cost of shopping cart with no taxes is: " + shoppingCartWithNoTaxes);
console.log("Cost of taxes is: " + costOfTaxes);
console.log("Total Cost of shopping cart is: " + shoppingCartTotal.toFixed(2));
